apiVersion: v1
kind: Service
metadata:
  name: key-value-service
  labels:
    app: key-value-app
spec:
  type: NodePort
  selector:
    app: key-value-app
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30007
