apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-keyvaluedb-init
  labels:
    app: mongodb
data:
  mongo-init.js: |
    const dbName = process.env.DB_NAME;
    const dbUsername = process.env.DB_USERNAME;
    const dbPassword = process.env.DB_PASSWORD;

    db = db.getSiblingDB(dbName);

    console.log(`INITIALIZING : ${dbName}`);
    console.log(`INITIALIZING : Creating user ${dbUsername}`);

    db.createUser({
      user: dbUsername,
      pwd: dbPassword,
      roles: [
        {
          role: 'readWrite',
          db: dbName,
        },
      ],
    });
    console.log(`INITIALIZING : Success`);